set(HEADER_FILE "${HEADER_DIR}/src/include/build_number.h")
set(CACHE_FILE "BuildNumberCache.txt")

#Reading data from file + incrementation
IF(EXISTS ${CACHE_FILE})
    file(READ ${CACHE_FILE} BUILD_NUM)
    math(EXPR BUILD_NUM "${BUILD_NUM}+1")
ELSE()
    set(BUILD_NUM "1")
ENDIF()

#Update the cache
file(WRITE ${CACHE_FILE} "${BUILD_NUM}")

#Create the header
file(WRITE ${HEADER_FILE} "/* WARNING: Do NOT modify this file.\n * This file is automatically generated\n*/"
    "\n#ifndef BUILD_NUM_H_\n#define BUILD_NUM_H_\n\n#define BUILD_NUMBER ${BUILD_NUM}\n\n#endif")