#ifndef NODE_IDS_H_
#define NODE_IDS_H_

#define OPCUA_NODE_NAMESPACE_MAIN                       2

#define OPCUA_NODE_ID_SOFTWARE_VERSION                  2117
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_MOTION_X       2133
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_MOTION_Y       2134
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_MOTION_Z       2135
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_VELOCITY_FL    2137
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_VELOCITY_FR    2138
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_VELOCITY_RL    2139
#define OPCUA_NODE_ID_KINEMATICS_FORWARD_VELOCITY_RR    2140
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_MOTION_X       2143
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_MOTION_Y       2144
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_MOTION_Z       2145
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_VELOCITY_FL    2147
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_VELOCITY_FR    2148
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_VELOCITY_RL    2149
#define OPCUA_NODE_ID_KINEMATICS_INVERSE_VELOCITY_RR    2150

#endif